//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationApp.AppFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelledTrip
    {
        public int Id { get; set; }
        public int IdRoute { get; set; }
        public int IdTrain { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual Train Train { get; set; }
    }
}
