//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationApp.AppFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int Id { get; set; }
        public System.DateTime DateOfInspection { get; set; }
        public int LocomotiveAge { get; set; }
        public int IdLocomotive { get; set; }
    
        public virtual Locomotive Locomotive { get; set; }
    }
}
