//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationApp.AppFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocomotiveDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocomotiveDriver()
        {
            this.Locomotive = new HashSet<Locomotive>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime MedicalInspection { get; set; }
        public string Gender { get; set; }
        public decimal Salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locomotive> Locomotive { get; set; }
    }
}
