//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationApp.AppFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbStationEntities : DbContext
    {
        public DbStationEntities()
            : base("name=DbStationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brigade> Brigade { get; set; }
        public virtual DbSet<CancelledTrip> CancelledTrip { get; set; }
        public virtual DbSet<DelayedTrip> DelayedTrip { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Inspection> Inspection { get; set; }
        public virtual DbSet<Locomotive> Locomotive { get; set; }
        public virtual DbSet<LocomotiveDriver> LocomotiveDriver { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<RouteCategory> RouteCategory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Train> Train { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
