//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationApp.AppFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public string ArePassed { get; set; }
        public string AreUnbought { get; set; }
        public int IdRoute { get; set; }
        public Nullable<int> IdPassenger { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Route Route { get; set; }
    }
}
